### ISSUE TITLE
Severe flickering for home page, Chrome on Linux

### ISSUE THREAD

**Issue by klausw** [supermedium/moonrider#152]
On my Linux desktop machine using Chrome 108.0.5359.71, the home page flickers severely. This isn't always happening, it switches between normal display and flickering every few seconds.

Here's a video - photosensitivity warning, extreme flashing / flickering. (Hence this bug report.)

https://photos.app.goo.gl/Y7UG1koajfVJrd4k7

Here's the GPU info:

| key | value |
| ----- | ----- |
| GL_VENDOR | Google Inc. (Intel) |
| GL_RENDERER | ANGLE (Intel, Vulkan 1.3.224 (Intel(R) UHD Graphics 620 (WHL GT2) (0x00003EA0)), Intel open-source Mesa driver-22.2.0) |
| GL_VERSION | OpenGL ES 2.0.0 (ANGLE 2.1.19724 git hash: ceec659ac60b) |

**Comment by klausw** [comment]
For completeness, here's the JS console output, though it doesn't look very illuminating:

```
A-Frame Version: 1.1.0 (Date 2021-02-02, Commit #e9659ff8e)
index.js:94 THREE Version (https://github.com/supermedium/three.js): ^0.124.2
index.js:96 WebVR Polyfill Version: ^0.10.12
browser.js:111 core:schema:warn Default value `false` does not match type `number` in component `layout` 
browser.js:111 core:a-assets:warn Cross-origin element (e.g., <img>) was requested without `crossorigin` set. A-Frame will re-request the asset with `crossorigin` attribute set. Please set `crossorigin` on the element (e.g., <img crossorigin="anonymous">)  null
7browser.js:111 core:a-entity:warn Tried to remove `Object3D` of type:  mesh which was not defined.
build.js?v=3:342 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
initContext @ build.js?v=3:342
4browser.js:111 core:a-entity:warn Tried to remove `Object3D` of type:  mesh which was not defined.
build.js?v=3:342 Uncaught TypeError: Cannot set properties of undefined (setting 'visible')
    at i.renderItemsInPlace (build.js?v=3:342:60759)
    at i.<anonymous> (build.js?v=3:342:60337)
    at i.onStateUpdate (build.js?v=3:342:62323)
    at AFRAME.registerSystem.dispatch (build.js?v=3:342:53760)
    at HTMLElement.<anonymous> (build.js?v=3:342:54656)
    at HTMLElement.<anonymous> (a-node.js:263:16)
    at i.search (build.js?v=3:1291:110570)
    at i.update (build.js?v=3:1291:108992)
    at i.initComponent (component.js:330:10)
    at i.updateProperties (component.js:302:12)
three.js:32869 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
getContext @ three.js:32869
10browser.js:111 core:a-entity:warn Tried to remove `Object3D` of type:  mesh which was not defined.
build.js?v=3:342 [headfist] false
browser.js:111 core:schema:warn Unknown property `model` for component/system `generic-tracked-controller-controls`. 
build.js?v=3:342 [headfist] false
browser.js:111 core:schema:warn Unknown property `model` for component/system `generic-tracked-controller-controls`. 
30browser.js:111 core:a-entity:warn Tried to remove `Object3D` of type:  sound which was not defined.
234browser.js:111 core:a-entity:warn Tried to remove `Object3D` of type:  mesh which was not defined.
build.js?v=3:342 Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD
build.js?v=3:342 [gpu-preloader] Error preloading, image not loaded fn
preloadTexture @ build.js?v=3:342
build.js?v=3:342 [gpu-preloader] Error preloading, image not loaded fn
preloadTexture @ build.js?v=3:342
build.js?v=3:342 [gpu-preloader] Error preloading, image not loaded fn
```

**Comment by dmarcos** [comment]
Thanks. I wonder if this is exclusive to Linux. It doesn't reproduce on my devices OSX and iOS
